First
DrRedyx/employee pull request #1
Opened 2021-12-08 21:45 UTC by DrRedyx

2021-12-09 11:03 UTC, Avenirre approved these changes

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeNotFind.java
> +public class EmployeeNotFind extends RuntimeException{
В именах классов-исключений на конце пишется Exception

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeController.java
> +            throw new StateIsFull();
В контроллере никакой логики быть не должно, все выкидывания исключений находятся в сервисе

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeService.java
> +                break;
return employee;

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeService.java
> +        if (employee != null) {
После цикла выбрасывается исключение.

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeService.java
> +            return null;
Никаких null возвращать не надо

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeService.java
> +            if (employees[i].getFirstName().equals(firstname) && employees[i].getLastName().equals(lastname)) {
Здесь используется метод equals из Employee

2021-12-09 11:03 UTC, Avenirre commented on src/main/java/com/example/employee/EmployeeService.java
> +                employee = employees[i];
В методе не происходит удаления, его нужно доработать

2021-12-14 12:25 UTC, Avenirre approved these changes

2021-12-16 23:04 UTC, OKrylov approved these changes
Отличная работа! Все задания выполнены корректно, по коду замечаний нет. Продолжайте в том же духе!

2021-12-23 10:30 UTC, OlgaLugacheva requested changes

2021-12-23 10:30 UTC, OlgaLugacheva commented on src/main/java/com/example/employee/EmployeeServiceImpl.java
> +    private final Map <Integer, Employee> employees;
По заданию сотрудник  c одним ФИО должен существовать только в одном экземпляре, корректно добавлялся и удалялся, поэтому стоит использовать в качестве ключа его ФИО

2021-12-23 10:30 UTC, OlgaLugacheva commented on src/main/java/com/example/employee/EmployeeServiceImpl.java
> +    }
Не вижу метода findAllEmployees, возможно, его стоит добавить, чтобы вывести все элементы коллекции

2021-12-23 10:30 UTC, OlgaLugacheva commented on src/main/java/com/example/employee/EmployeeServiceImpl.java
> +        if (employees.containsKey(num)) {
Если ты все же решишь изменить ключ на String, то либо нужно будет поменять методы find и delete. Либо добавить в класс Empltyee статическое поле num - счетчик и  фильтровать значения мапы по нему    примерно так employees.entrySet().stream().filter(x -> x.getValue().getNum().equals(num)).findFirst().get()

2021-12-24 05:19 UTC, OlgaLugacheva approved these changes

2022-01-19 06:44 UTC, Avenirre approved these changes

2022-01-19 06:44 UTC, Avenirre commented on src/main/java/com/example/employee/DepartmentServiceImpl.java
> +                .get();
Желательно выбрасывать исключение, если работника не найдено (никого нет в отделе или нет такого отдела вообще)

2022-01-19 06:44 UTC, Avenirre commented on src/main/java/com/example/employee/DepartmentServiceImpl.java
> +                .get();
См. предыдущий метод

2022-01-23 14:20 UTC, OKrylov approved these changes
Отличная работа! По задачам все верно, оставил несколько некритичных замечаний/советов. Продолжайте в том же духе!

2022-01-23 14:20 UTC, OKrylov commented on src/main/java/com/example/employee/EmployeeServiceImpl.java
> +            StringUtils.capitalize(lastname);
данный метод возвращает новую модифицированную строку, а не меняет переданную (строки неизменяемы)

2022-01-23 14:20 UTC, OKrylov commented on src/main/java/com/example/employee/EmployeeServiceImpl.java
> +            StringUtils.capitalize(lastname);
логика повторяется в методах, можно вынести в отдельный метод по проверке и модификации каждого параметра

2022-01-23 14:20 UTC, OKrylov commented on src/main/java/com/example/employee/StringIsNotAlphabeticException.java
> +public class StringIsNotAlphabeticException extends RuntimeException{
как минимум стоит добавить конструктор, что вызывает super и передает некое детализированное сообщение об ошибке

2022-02-03 10:11 UTC, OKrylov requested changes
В целом практически идеально выполненная работа. Есть небольшие замечания по логике проверок в сервисах и в самих тестах, не все они проходят. Я оставил несколько небольших замечаний по коду, просьба обратить внимание

2022-02-03 10:11 UTC, OKrylov commented on src/main/java/com/example/employee/DepartmentServiceImpl.java
> +        if (department != null || department < 5 || department != 0) {
дублируемый код, лучше вынести в отдельный метод

2022-02-03 10:11 UTC, OKrylov commented on src/main/java/com/example/employee/DepartmentServiceImpl.java
> +        if (department != null || department < 5 || department != 0) {
само условие некорректное, мы опрашиваем через ИЛИ, то есть достаточно только одного из условий, из-за чего некоторые тесты не проходят

2022-02-03 10:11 UTC, OKrylov commented on src/test/java/com/example/employee/DepartmentServiceImplTest.java
> +                () -> departmentService.getMinSalaryDepartmentEmployee(0));
Тест не проходит. Нужно передавать не нулевой, но и не существующий отдел.

2022-02-03 10:11 UTC, OKrylov commented on src/test/java/com/example/employee/DepartmentServiceImplTest.java
> +        when(testMock.getAll()).thenReturn(TRUE_LIST);
данную строку нужно удалить, поскольку она никак не влияет на исход теста (после правок проверки номера отдела в сервисе)

2022-02-03 10:11 UTC, OKrylov commented on src/test/java/com/example/employee/DepartmentServiceImplTest.java
> +        when(testMock.getAll()).thenReturn(TRUE_LIST);
данную строку нужно удалить, поскольку она никак не влияет на исход теста (после правок проверки номера отдела в сервисе)

2022-06-24 20:26 UTC, merged